### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by JonS87** [Denis070/TInvestProfit#1]
Помоги пожалуйста починить проект, я с пайтаном мягко говоря на вы,
но в Profit закинул несколько, пока что кривых расчетов, но самое главное добавил функцию "Category", проверил работу, всё работает, в write прописал добавление еще 1 листа и запись в него результата этой функции, запускаю проект и вижу ошибку "Нет модуля под именем inc" в размеделе "from inc.profit import Profit". [inc.zip](https://github.com/AzzraelCode/TInvestProfit/files/7540771/inc.zip)
Почему папка inc может искаться как модуль, как это исправить?

**Comment by AzzraelCode** [comment]
Три дня назад человек приходил с похожей проблемой https://www.youtube.com/watch?v=MEreqcTRq6c&lc=Ugw0zh6MPEO41EM2MjJ4AaABAg. После чего я чуть поправил этот репозиторий. Если ты клонировал репо раньше чем 3 дня назад, то попробуй клонировать вновь, возможно поможет. 
~~
Если нет, то, вероятно, проблема в https://docs.python.org/3/using/cmdline.html#environment-variables . Если у тебя питон по виндой, то при установке нужно ставить галочку в окне установки рядом с Add Python 3.*** PATH https://docs.blender.org/manual/ru/2.80/_images/about_contribute_install_windows_installer.png и перезагрузить комп.
~~
Напиши по итогу.

**Comment by JonS87** [comment]
Спасибо за ответ, но сегодня включил комп, а всё работает, ошибок нет. 
Галочку в окне установки рядом с Add Python 3.*** PATH я ставил.
